### ISSUE TITLE
Filter Join collection

### ISSUE THREAD

**Issue by josx** [Bill4Time/mongo-fast-join#1]
Is there any way to do something like SQL WHERE on Join Collections?
Is it on your schedule of work?

**Comment by khous** [comment]
Not currently, I can see that that could be useful though. To be clear, right now it is coded to only filter the initial query set. The records found for joining are what match the the primary (or composite) keys from the query set. Off the top of my head, I feel like adding filtering at each stage of the join wouldn't be too difficult. 

This all goes along with the obligatory "you may want to consider inlining documents / redesigning your schema" warning.

If this issue gets some votes, we will probably address it, and probably will anyway. Thanks for your participation! Sorry that it took three days to get back to you.

**Comment by khous** [comment]
Resolved by pull request #2 and #1
