### ISSUE TITLE
example how to use 

### ISSUE THREAD

**Issue by februarythom** [Bill4Time/mongo-fast-join#3]
how to use it, there are examples of its use?

**Comment by khous** [comment]
Yeah, look at the readme

**Comment by chinamerp** [comment]
could you tell me why the program need the $or match?
queryArray = [ { $match: inQuery }, { $match: orQuery } ];

**Comment by khous** [comment]
Please reference the line in question

**Comment by maddy2308** [comment]
could you provide a full blown example with just two collections. The one provided in readme file is not that self explainatory.
