### ISSUE TITLE
How is it possible to sort results?

### ISSUE THREAD

**Issue by no-glue** [Bill4Time/mongo-fast-join#4]
How is it possible to sort results after join?

**Comment by khous** [comment]
If you would like to sort the results, provide the standard mongo sort arguments to the options of the query function. This will only work if the original collection of documents has the field that you would like to sort on. 

If you wish to sort on a field that is present on a document being joined in, you must use a standard Array.prototype.sort on the resultant array.

This utility could help if you want to perform a complex sort, it's not well documented as of yet:
https://github.com/Bill4Time/complex-sort
